const ACTION_TYPES = {
  GET_ALL_GROUPS : "GET_ALL_GROUPS",
  SEARCH_GROUP_BY_NAME : "SEARCH_GROUP_BY_NAME",
  GET_ALL_USERS : "GET_ALL_USERS",  
  CREATE_GROUP : "CREATE_GROUP",
  DELETE_GROUP_SUCCESS : "DELETE_GROUP_SUCCESS",
  DELETE_GROUP_FAILURE : "DELETE_GROUP_FAILURE",
  UPDATE_GROUP_SUCCESS : "UPDATE_GROUP_SUCCESS",
  UPDATE_GROUP_FAILURE : "UPDATE_GROUP_FAILURE",
  CREATE_USER : "CREATE_USER",
  CLEAN_DETAIL : "CLEAN_DETAIL",
  SEARCH_CATE_GROUPS : "SEARCH_CATE_GROUPS",
  SEARCH_INICIATE_GROUPS : "SEARCH_INICIATE_GROUPS",
  SEARCH_FAMILIA_GROUPS : "SEARCH_FAMILIA_GROUPS",
  GET_ALL_PATRULLEROS : "GET_ALL_PATRULLEROS",
  CREAR_PATRULLERO : "CREAR_PATRULLERO",
  ELIMINAR_PATRULLERO_EXITO : "ELIMINAR_PATRULLERO_EXITO",
  ELIMINAR_PATRULLERO_FRACASO : "ELIMINAR_PATRULLERO_FRACASO",
  MODIFICAR_PATRULLERO_EXITO : "MODIFICAR_PATRULLERO_EXITO",
  MODIFICAR_PATRULLERO_FRACASO : "MODIFICAR_PATRULLERO_FRACASO",
  ERROR : "ERROR",

}
    
 export default ACTION_TYPES